### ISSUE TITLE
Return error message

### ISSUE THREAD

**Issue by ukitazume** [sysdiglabs/terraform-provider-sysdig#102]
# Summary

Sysdig terraform provider returns just HTTP status when errors happen. It should include the error message.

# For example

As a wrong macro, it must start with 'or' or 'and' but the below example doesn't start with these.

```
resource "sysdig_secure_macro" "this" {
  name      = "access_log_files"
  condition = "container"
  append    = true
}
```
When I apply it, terraform returns without error messages like that

```
$  terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # sysdig_secure_macro.this will be created
  + resource "sysdig_secure_macro" "this" {
      + append    = true
      + condition = "container"
      + id        = (known after apply)
      + name      = "access_log_files"
      + version   = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

sysdig_secure_macro.this: Creating...
╷
│ Error: 400 Bad Request
│
│   with sysdig_secure_macro.this,
│   on macro.tf line 1, in resource "sysdig_secure_macro" "this":
│    1: resource "sysdig_secure_macro" "this" {
```

The API looks return error message via UI.
![Screen Shot 2021-05-27 at 13 45 17](https://user-images.githubusercontent.com/271027/119767758-7210d180-bef2-11eb-9d31-8c8b44109258.png)

##  versions of the example
```
$  terraform version
Terraform v0.15.1
on darwin_amd64
+ provider registry.terraform.io/sysdiglabs/sysdig v0.5.14
```

**Comment by tembleking** [comment]
Thanks for reporting this @ukitazume, I am going to close this issue, since it should be fixed in [v0.5.15](https://github.com/sysdiglabs/terraform-provider-sysdig/releases/tag/v0.5.15). If this continues to happen, feel free to open it again.
