### ISSUE TITLE
Add support Image Scanning Policy and the gates

### ISSUE THREAD

**Issue by ukitazume** [sysdiglabs/terraform-provider-sysdig#103]
I'd like you to add scanning policy gates
https://docs.sysdig.com/en/scanning-policy-gates-and-triggers.html

**Comment by ukitazume** [comment]
I need it. could you reopen it? :)

**Comment by ukitazume** [comment]
could you reopen it?

**Comment by tembleking** [comment]
Sure, reopening it @ukitazume

**Comment by tembleking** [comment]
It has not been prioritized yet tho :slightly_frowning_face:

**Comment by ukitazume** [comment]
@tembleking Could you reopen this?
