### ISSUE TITLE
Add support for CIS Benchmark tasks; Custom Selection

### ISSUE THREAD

**Issue by oke-py** [sysdiglabs/terraform-provider-sysdig#104]
We'd like to run kube-bench and linux-bench in some Kubernetes clusters monitored by different Sysdig Secure clusters.
We don't need to run all tests of each benchmark, and so Custom Selection will be suitable.

Actually, the priority is low compared to Image Scanning Policy etc., but we'd be happy if CIS Benchmark settings be supported.

**Comment by ukitazume** [comment]
has it been solved by https://github.com/sysdiglabs/terraform-provider-sysdig/pull/119 ?
