### ISSUE TITLE
Support for PromQL Alerts

### ISSUE THREAD

**Issue by stuwatts** [sysdiglabs/terraform-provider-sysdig#108]
We're starting to make more use of PromQL based alerts.  I appreciate they're in Beta at the moment, but it would be great to get support for these in the TF provider.  We can't adopt the provider until PromQL alerts are supported.

**Comment by tembleking** [comment]
Thanks @stuwatts for the feedback, let me talk with the team and prioritize this Feature Request :slightly_smiling_face:

**Comment by allen-servedio** [comment]
Hi @tembleking - we have also hit a point where we could make use of this feature. Has your team decided if they will be taking this up and - if so - any rough idea on when? Thanks either way!

**Comment by jon-ruckwood** [comment]
Possibly related to https://github.com/sysdiglabs/terraform-provider-sysdig/pull/123

**Comment by DenysChekirda** [comment]
Fix proposed by @jon-ruckwood is working in case of this issue. I've been able to create a prometheus alert.

**Comment by tembleking** [comment]
This can be closed now, since it has been implemented by #129
