### ISSUE TITLE
Add user and team management for Sysdig Secure

### ISSUE THREAD

**Issue by rung** [sysdiglabs/terraform-provider-sysdig#11]
Hi, I would like to add user/team management to this terraform provider.
Can I send PR for this feature?
And if It's ok, Could you guys review my Terraform resource design?

## Usecases
- Companies, which manages user and teams via Terraform like our company,  want to manage Sysdig users and teams by this provider.

#### Users (Sample)
```hcl
resource "sysdig_users" "sample_users" {
  email      = "sample@example.com"
  system_role = "ROLE_CUSTOMER" # Optional, Default = "ROLE_USER"
  first_name = "John"
  last_name  = "Smith"
}
```
- sysdig user is shared with secure and monitor, so resource name is `sysdig_users` (not `sysdig_secure_users`)

#### Teams (Sample)
```hcl
resource "sysdig_secure_teams" "sample_teams" {
  name        = "sample-team"
  description = "sample"
  scope_by      = "container" # Optional, Default:container
  filter      = "container.id = \"000266b5ebab\" and container.image.digest = \"sha256:724489a791e7ead89e1b44cf7cdbaf34bd04022973b835cfa834c95e1bcc5e10\"" # Optional, Default=""
  use_sysdig_capture = true # Optional, Default:true

  advanced_users = [ # Optional
    "sample@example.com"
  ]
  view_only_users = [ # Optional
    sysdig_secure_users.sample_users.email,
  ]
  team_managers = [ # Optional
    "sample@example.com"
  ]
  standard_users = [ # Optional
    "sample@example.com"
  ]
}
```

**Comment by tembleking** [comment]
Hi @rung, thank you for willing to contribute to this project, your PR is very welcome :heart:. As of the resource designs, they look pretty good to me :blush:.

**Comment by nestorsalceda** [comment]
I only have one concern and is that I prefer to name the resource using singular, this means:

`resource "sysdig_users" "sample_users" {`

I prefer to call this: 

`resource "sysdig_user" "sample_users" {`

I mean, we are creating just one user or one team. But the other things looks awesome to me.

Please, ping me or Fede if you need more guidance and I'm also open to have some session for mob / pair programming if you have any trouble :)

Thank you very much!

**Comment by rung** [comment]
@tembleking @nestorsalceda 
Thank you for your review and help!  :)

**Comment by rung** [comment]
@tembleking @nestorsalceda 
Hi, I re-considered the resource design of `sysdig_secure_team` while implementing it.
How about this new design? I welcome any suggestions!

```hcl
resource "sysdig_secure_team" "sample" {
  name               = "sample-team"
  description        = "sample"
  scope_by           = "container"
  filter             = "container.image.repo = \"sysdig/agent\""
  use_sysdig_capture = false

  user_roles {
    email = "sample@example.com"
    role  = "ROLE_TEAM_STANDARD"
  }

  user_roles {
    email = "sample2@example.com"
    role  = "ROLE_TEAM_EDIT"
  }
}
```

I changed `user_roles`. I used `TypeList` (`advanced_users, view_only_users, team_managers, standard_users`) for old design, but I started to use `TypeSet`.

### Reason
- The new design is close to API design.
  - Sysdig API(api/teams): 
  ```json
  {"team":{"userRoles":["userName":"sample@example.com","role":"ROLE_TEAM_MANAGER"}, 
  {"userName":"sample2@example.com","role":"ROLE_TEAM_READ"}],"name":"sample-team",...
  ```
  - Python sdc client
https://github.com/draios/python-sdc-client/blob/165853c/sdcclient/_common.py#L800:L804

- I researched other Terraform providers. 
  - The new `user_roles` is similar to `access` of [BigQuery Dataset on GCP](https://www.terraform.io/docs/providers/google/r/bigquery_dataset.html)
    <img src="https://user-images.githubusercontent.com/1150301/75963065-36ae6f80-5f08-11ea-9517-050096b8324a.png" width="260px">
  - It seems it's also a common design.
- I initially thought `TypeSet` is challenging to use for user/team management when I made this issue. 
  - Companies like us manage users using list like this. and I thought it's not easy to convert teamA(email address list)(`TypeList`) to user_roles (`TypeSet`) on Terraform.
```hcl
teamA = [sample@example.com, sample@example.com]
```

  - but I found an easy way to convert using `dynamic` and `for_each`
    - so I feel new design is good from usability too.
```hcl
locals {
  teamA = ["sample@example.com", "sample2@example.com"]
}

resource "sysdig_secure_team" "sample" {
  name               = "sample-team2"
  description        = "sample2"
  scope_by           = "container"
  filter             = "container.image.repo = \"sysdig/agent\""
  use_sysdig_capture = false

  dynamic "user_roles" {
    for_each = local.teamA
    content {
      email = user_roles.value
      role  = "ROLE_TEAM_STANDARD"
    }
  }
}
```
- Ref: https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each/

Thanks!

**Comment by tembleking** [comment]
Looks good to me @rung! Thanks for your work :slightly_smiling_face:

**Comment by rung** [comment]
Thank you for your review.
These PR are merged. so I'll close this issue.

**Comment by dprosper** [comment]
I realize this issue is closed and so is the associated PR, a question still.   

The code for this seems tightly coupled to Sysdig Secure. I use Sysdig Monitor, and I don't use Sysdig Secure.  I was under the impression that Teams was a Sysdig Platform capability and thus is the same code/backend for both Secure and Monitor.  Would it make sense to make this more agnostic from the product, so that it can be used for both Secure and Monitor? 

@tembleking @rung

**Comment by rung** [comment]
@dprosper 
In my understanding, user is under the common Sysdig Platform. but team is not under the common Sysdig Platform.
(When I create a new team on Sysdig Secure,  I can't see the team on Sysdig Monitor.)

So about team, I think it would be great to create new `resource "sysdig_monintor_team"` for Sysdig Monitor.
And about user, if there is a users who don't use `Sysdig Secure`, it's good to use `Sysdig Monitor API Token` for creating new user. (I'm not sure but every Sysdig user has Sysdig Monitor licenses, right?)

@tembleking How do you think?

**Comment by tembleking** [comment]
Hi @dprosper, as @rung mentioned, teams are not shared between Monitor and Secure, but the data sent to the API is pretty much the same, so making a `sysdig_monitor_team` resource should be really easy.

**Comment by rung** [comment]
@tembleking Thank you for your clarification.

One question about `sysdig_user`.
Are there customers who don't use Sysdig Monitor? Users is shared between Monitor and Secure.
So if there is no costomer who uses Sysdig Secure only, I want to change api from Secure to Monitor on `sysdig_user`.

**Comment by tembleking** [comment]
@rung Don't worry, a user is created for both Monitor and Secure. To be able to access Monitor, the user needs to be added to a Monitor group and to access to Secure, the user must be added to a Secure group, so it's fine to leave it as `sysdig_user`

**Comment by dprosper** [comment]
@rung so will you be taking up the updates to include `sysdig_monitor_team`?  

On a side, I noticed that the Team struct does not include all possible options, i.e. canUseBeaconMetrics, canUseAWSMetrics, canUseCustomEvents, ... These default to true I believe by the REST API if you do not set them to false in your payload.

**Comment by rung** [comment]
@tembleking 
Thank you for your reply!
I mean, should I change `sysdigSecureClient` to `sysdigMonitorClient` on `sysdig_user`?
- example
https://github.com/draios/terraform-provider-sysdig/blob/78668765e04278c898a83e00437133996b08d63f/sysdig/resource_sysdig_user.go#L50

I thought more customers can use `sysdig_user` if I changed client form secure to monitor. 
As @dprosper said, customers like him don't use Sysdig Secure. So they can't use current `sysdig_user` resource because it requires Sysdig Secure API Token.

**Comment by tembleking** [comment]
Yeah that would be a good change @rung . Also right now, the Provider requires the user to add the API Token for both Monitor and Secure. This could be problematic for users that only have one or the other.

**Comment by dprosper** [comment]
@rung Are you still pursuing the updates to add the support for Monitor? Maybe I can help if you can share how far you got with it.

**Comment by tembleking** [comment]
Thanks for your contributions @rung, I'll support this issue.

It's related to #23

**Comment by tembleking** [comment]
The `sysdig_user` resource should now be usable with either Monitor or Secure token since https://github.com/draios/terraform-provider-sysdig/commit/b70e1acb20d06400d96324b9a1437f81585891b0.

**Comment by dprosper** [comment]
@tembleking I was trying to create a team in Sysdig Monitor, I think that is still missing.  

Should these lines also be changed to use the common client: 
https://github.com/draios/terraform-provider-sysdig/blob/290e398440f442388bca19e8243618f689ef9e26/sysdig/resource_sysdig_secure_team.go#L103
https://github.com/draios/terraform-provider-sysdig/blob/290e398440f442388bca19e8243618f689ef9e26/sysdig/resource_sysdig_secure_team.go#L130
https://github.com/draios/terraform-provider-sysdig/blob/290e398440f442388bca19e8243618f689ef9e26/sysdig/resource_sysdig_secure_team.go#L146

and maybe rename the resource from `resource_sysdig_secure_team.go` to `resource_sysdig_team.go` ?

**Comment by dprosper** [comment]
After reviewing this a bit more, I have come to realize there are a few additional changes that would be required for this to work as I need it.  I will make the changes and create a PR.

**Comment by dprosper** [comment]
I added the pull request here, however note that I am not in a position to fully test it with Secure. https://github.com/draios/terraform-provider-sysdig/pull/31

**Comment by tembleking** [comment]
This has already been implemented. Closing this issue.
