### ISSUE TITLE
Create a PagerDuty notification channel failed with "panic: Invalid diagnostic: empty summary. This is always a bug in the provider implementation"

### ISSUE THREAD

**Issue by moses3009** [sysdiglabs/terraform-provider-sysdig#169]
Tried both providers 0.5.36 and 0.5.35 and got similar errors.
0.5.36 version:
==================
sysdig_monitor_notification_channel_pagerduty.pagerduty: Creating...
╷
│ Error: Plugin did not respond
│
│   with sysdig_monitor_notification_channel_pagerduty.pagerduty,
│   on main.tf line 7, in resource "sysdig_monitor_notification_channel_pagerduty" "pagerduty":
│    7: resource "sysdig_monitor_notification_channel_pagerduty" "pagerduty" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call.
│ The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-sysdig_v0.5.36 plugin:

panic: Invalid diagnostic: empty summary. This is always a bug in the provider implementation

goroutine 67 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/internal/plugin/convert.DiagsToProto({0xc00058f740, 0x1, 0xc00022f7d0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/internal/plugin/convert/diagnostics.go:72 +0x2b3
github.com/hashicorp/terraform-plugin-sdk/v2/internal/plugin/convert.AppendProtoDiag({0x0, 0x0, 0x0}, {0xbc0360, 0xc0004668a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/internal/plugin/convert/diagnostics.go:25 +0x99
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00011c798, {0xdbdeb8, 0xc0004de380}, 0xc000462410)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:978 +0xdcb
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000154c80, {0xdbdf60, 0xc0003dc180}, 0xc0004fe0e0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc741e0, 0xc000154c80}, {0xdbdf60, 0xc0003dc180}, 0xc0004e6060, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000140700, {0xdcbe70, 0xc00029a1a0}, 0xc00017e5a0, 0xc00043f800, 0x1305800, 0x0)
        google.golang.org/grpc@v1.43.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000140700, {0xdcbe70, 0xc00029a1a0}, 0xc00017e5a0, 0x0)
        google.golang.org/grpc@v1.43.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.43.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.43.0/server.go:919 +0x294

Error: The terraform-provider-sysdig_v0.5.36 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
=========================================================

**Comment by wideawakening** [comment]
think this may be related to #170 let's see when its merged if it fises

**Comment by wideawakening** [comment]
could we get some feedback on this @moses3009 ?

**Comment by moses3009** [comment]
@wideawakening I can confirm that exception not appear anymore. Now I get unauthorized access using the right api key.

**Comment by wideawakening** [comment]
that's odd, i just throw the tests and they're passing
https://github.com/sysdiglabs/terraform-provider-sysdig/actions/runs/2189089736
