### ISSUE TITLE
Sysdig Provider uses deprecated module

### ISSUE THREAD

**Issue by skadz** [sysdiglabs/terraform-provider-sysdig#182]
The template module has been deprecated for some time:

https://registry.terraform.io/providers/hashicorp/template/latest/docs

It's currently required by the sysdig provider which means sysdig's terraform code does not work on Mac M1 (and any other arm64 machines).  

Can you guys please update to use templatefile which is the correct way to do templates these days:

https://www.terraform.io/language/functions/templatefile

This was found by using the terraform providers command which showed:

```
├── module.sysdig
│   ├── provider[registry.terraform.io/sysdiglabs/sysdig]
│   ├── provider[registry.terraform.io/hashicorp/aws]
│   ├── module.fargate-orchestrator-agent
│       ├── provider[registry.terraform.io/hashicorp/template]
│       └── provider[registry.terraform.io/hashicorp/aws]
```

**Comment by wideawakening** [comment]
similar to your other issue, this one seems more related to  https://github.com/sysdiglabs/terraform-aws-fargate-orchestrator-agent 
will ping devs there though :)

**Comment by wideawakening** [comment]
closing this. issue to be addressed in its specific repo :)
https://github.com/sysdiglabs/terraform-aws-fargate-orchestrator-agent/issues/5
