### ISSUE TITLE
cloud_account alias keeps changing

### ISSUE THREAD

**Issue by skadz** [sysdiglabs/terraform-provider-sysdig#183]
It appears that there is no place in the code to set this alias, but every time I refresh my terraform it gets set and then when I go to apply, it goes to unset it again:

```
  # module.sysdig.module.sysdig[0].module.cloud_bench[0].sysdig_secure_cloud_account.cloud_account["XXXXXXXXXX"] will be updated in-place
  ~ resource "sysdig_secure_cloud_account" "cloud_account" {
      - alias          = "my-account-alias-staging" -> null
        id             = "XXXXXXXXXX"
        # (5 unchanged attributes hidden)
    }
```

Can this become a variable that can be set or have it automatically set and not have this constant switching?  It is very annoying when you have no changes in your infrastructure, but you need to apply anyways because it sees this as a change.

**Comment by wideawakening** [comment]
hey @skadz !

provider does enable [sysdig cloud-account alias setup](https://github.com/sysdiglabs/terraform-provider-sysdig/blob/master/website/docs/r/secure_cloud_account.md#argument-reference), guess you're asking for a fix on some of the secure-for-cloud. modules.

we got it under radar already for all aws/gcp/azure modules.
