### ISSUE TITLE
sysdig_secure_policy severity should match UI

### ISSUE THREAD

**Issue by heydonovan** [sysdiglabs/terraform-provider-sysdig#196]
When creating a new policy from the UI, you are only presented with 4 options (High, Medium, Low, and Info). It is confusing when deciding on a number (do we want 0 or 1? both mean High). I think a string that says "high", would be more clear.

>[severity](https://registry.terraform.io/providers/sysdiglabs/sysdig/latest/docs/resources/secure_policy#severity) - (Optional) The severity of Secure policy. The accepted values are: 0, 1, 2, 3 (High), 4, 5 (Medium), 6 (Low) and 7 (Info). The default value is 4 (Medium).

**Comment by tembleking** [comment]
The severity in the policies is a priority inherited from Falco: https://falco.org/docs/rules/#rules 
The product maps the 0-3 to high, 4-5 to medium, 6 to medium and 7 to info.
