### ISSUE TITLE
Missing "Capture file name" attribute in sysdig_secure_policy

### ISSUE THREAD

**Issue by airadier** [sysdiglabs/terraform-provider-sysdig#197]
When defining a policy in the UI and enabling captures, there is a "File name" field that cannot be left empty.

The resource in the provider doesn't expose that attribute, so when a policy is created via the provider, the "File name" field is left empty, which causes the capture to fail, as it is stored locally on the agent rather than on Sysdig S3.

@lindawang-sysdig @timekillerj @garyhutchins FYI

**Comment by baskar-sd** [comment]
@airadier thanks for filing this. Do you know who is tasked to fixing this? It is pretty critical we fix this asap as it has caused issues with multiple customers. We will be adding a backend check to reject this as well.

**Comment by airadier** [comment]
Hi @baskar-sd , no idea who is tasked. Originally the Cloud Native Team was maintaining the Terraform Provider, but as far as I know the responsibility should be split so each team maintains the provider corresponding to their APIs. So in this case I think the team maintaining the policies API should take care of this.

I can provide some support as I located the couple of points where the provider needs to be modified in order to support the new attribute:

- The schema of the resource, to add the new attributes inside the capture section (https://github.com/sysdiglabs/terraform-provider-sysdig/blob/a75db651c9080d1a76d3399e65ce90988a43352d/sysdig/resource_sysdig_secure_policy.go#L95) and expose them to the Terraform resource (and add new tests in https://github.com/sysdiglabs/terraform-provider-sysdig/blob/master/sysdig/resource_sysdig_secure_policy_test.go)
- The API client, so it includes the new fields as part of the request (I think we only need to change the function that makes the conversion from the terraform resource to secure API format in https://github.com/sysdiglabs/terraform-provider-sysdig/blob/a75db651c9080d1a76d3399e65ce90988a43352d/sysdig/resource_sysdig_secure_policy.go#L177 and the opposite conversion in https://github.com/sysdiglabs/terraform-provider-sysdig/blob/a75db651c9080d1a76d3399e65ce90988a43352d/sysdig/resource_sysdig_secure_policy.go#L137)

@tembleking might help confirming if the above is true, or there are any additional required changes

**Comment by airadier** [comment]
Reopening it, as the problem still applies.

**Comment by airadier** [comment]
It seems to be worse now. Instead of creating the policy but failing to execute captures, now it fails to create the resource with the error:

`Error: Capture name cannot be empty`

it looks like the backend is now enforcing this attribute, but it fails if it is missing.

**Comment by airadier** [comment]
Apparently the attribute is supported: https://registry.terraform.io/providers/sysdiglabs/sysdig/latest/docs/resources/secure_policy#name

but it should be made mandatory instead of optional :)

**Comment by airadier** [comment]
PR provided in https://github.com/sysdiglabs/terraform-provider-sysdig/pull/229
