### ISSUE TITLE
sysdig_secure_team - Missing options

### ISSUE THREAD

**Issue by omaen** [sysdiglabs/terraform-provider-sysdig#215]
Hi, 

When creating new teams with the provider, not all settings are configurable with terraform.
`use_sysdig_capture` is possible to set to `false`, but `Agent CLI` (which defaults to `true`) and `Rapid Response` is not possible to configure as of now.

![image](https://user-images.githubusercontent.com/17073840/200815084-72032a11-6d02-47b0-b68e-19efc110c4da.png)

Is this something you can add?

**Comment by wideawakening** [comment]
issue/feature request has been raised, but no clear immediate resolution in short-term, so PR is welcomed :)
