### ISSUE TITLE
specify query options

### ISSUE THREAD

**Issue by andreainnocenti** [sysdiglabs/terraform-provider-sysdig#252]
Hi team! we are trying to convert our panels created manually to terraform. In the panels that we created, we specified some options like:
<img width="836" alt="Screenshot 2023-02-14 at 10 03 51" src="https://user-images.githubusercontent.com/62945651/218689115-3513d332-fd8f-4f0a-81e4-5faf9f139374.png">

while in the panel created by terraform:
<img width="834" alt="Screenshot 2023-02-14 at 10 03 45" src="https://user-images.githubusercontent.com/62945651/218689299-a768b9bd-7e20-4952-bad9-78a986459481.png">

snippet of code:
```
panel {
    pos_x       = 0
    pos_y       = 0
    width       = 24
    height      = 8
    type        = "timechart"
    name        = "Overall Avg duration of incoming calls (Web Transaction Time)\n"


    query {
        promql = "sum(rate(ghostv1_http_server_duration_sum{$__scope}[$__interval]) ) / sum (rate(ghostv1_http_server_duration_count{$__scope}[$__interval]))"
        unit = "time"
        display_info {
            display_name                      = "Overall Avg duration of incoming calls "
            time_series_display_name_template = ""
            type                              = "stackedArea"
        }
    }
  }
```

do you have any suggestion? we would like to avoid to manually change the options for hundreds of panels

**Comment by andreainnocenti** [comment]
looking at https://us2.app.sysdig.com/api/public/docs/index.html#tag/Dashboard-V3/operation/createDashboardUsingPOST_4

I see that it's possible to send these values
<img width="771" alt="Screenshot 2023-02-14 at 10 41 52" src="https://user-images.githubusercontent.com/62945651/218697961-3cfe4f6f-6f8b-4bbd-b953-f0066b5dfc0d.png">

**Comment by filiptubic** [comment]
Hey @andreainnocenti formatting is added with 0.7.0 version. Im closing this.
