### ISSUE TITLE
specify the minInterval as dashboard setting

### ISSUE THREAD

**Issue by andreainnocenti** [sysdiglabs/terraform-provider-sysdig#263]
I would like to be able to specify the `Default PromQL Query Min. Interval`. For example in the UI:
<img width="853" alt="Screenshot 2023-03-09 at 12 12 47" src="https://user-images.githubusercontent.com/62945651/224007015-d409db00-f54b-4ff2-b91e-5813c99cac38.png">

it is possble via API 
<img width="859" alt="Screenshot 2023-03-09 at 12 13 36" src="https://user-images.githubusercontent.com/62945651/224007255-0b39d747-c49b-4cf4-8515-3215ceb7167b.png">

but it is not possible via Terraform

**Comment by andreainnocenti** [comment]
issue is still valid

**Comment by andreainnocenti** [comment]
issue is still valid

**Comment by andreainnocenti** [comment]
issue is still valid

**Comment by andreainnocenti** [comment]
issue is still valid

**Comment by IgorEulalio** [comment]
Hey @andreainnocenti, that feature was implemented as part of v1.21.0. Please reference the changelog here in case you have any questions: https://github.com/sysdiglabs/terraform-provider-sysdig/releases/tag/v1.21.0
