### ISSUE TITLE
Add provider to Terraform Registry

### ISSUE THREAD

**Issue by heydonovan** [sysdiglabs/terraform-provider-sysdig#41]
We are currently transitioning from 0.12 to 0.13, just need this provider to be on the registry:

https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-13/

**Comment by tembleking** [comment]
Hi @heydonovan, we just published the provider to the Terraform Registry: https://registry.terraform.io/providers/sysdiglabs/sysdig/latest 

Thanks for the feedback!
