### ISSUE TITLE
Creating team/zone scoped notification channels from an admin account

### ISSUE THREAD

**Issue by Gby56** [sysdiglabs/terraform-provider-sysdig#434]
Hi !

I'd like to setup a notification routing per team in my company, to dispatch findings/notifications to each team in their own slack channel for example (no point in dumping every single sysdig finding across all clusters, namespaces and teams in 1 slack channel...)
I don't think it's possible, even for an admin, to create a notification channel for another team (except maybe the poorly documented Team Email it seems, but I have no idea how it works)

The only solution I can think of: ask each team to do it themselves... or maybe through the API using a service account in each team, to setup a notification channel ?

**Comment by dbonf** [comment]
Hi, 

> I don't think it's possible, even for an admin, to create a notification channel for another team (except maybe the poorly documented Team Email it seems, but I have no idea how it works)

correct, currently you can create a notification channel that is usable by all the teams (the [default](https://registry.terraform.io/providers/sysdiglabs/sysdig/latest/docs/resources/monitor_notification_channel_slack#share_with_current_team)) or only by the team of the user that created it. This is also true using the UI or directly via API calls.

> The only solution I can think of: ask each team to do it themselves... or maybe through the API using a service account in each team, to setup a notification channel ?

If you have access to an API token of a user for each team, you can still use terraform configuring [multiple providers] (https://developer.hashicorp.com/terraform/language/providers/configuration#alias-multiple-provider-configurations), each one configured with the API token of a user for a particular team, and use them to create the notification channel related to the team of each provider.

Or, if that is acceptable, you can create notification channels shared with all the teams, and let each team select the correct one.

**Comment by Gby56** [comment]
It's definitely a suboptimal solution if I have to setup all these providers yep, and having a single slack channel with too many alerts is also probably going to just end up in a muted slack channel that nobody looks at...
Instead I resulted in extracting image findings using Zones, to create scopes on the clusters/namespaces, and uploading the findings to Defectdojo to group and dispatch findings per team.
