### ISSUE TITLE
"missing user's current team" on the provider while it's marked as optionnal

### ISSUE THREAD

**Issue by nicholas-bn** [sysdiglabs/terraform-provider-sysdig#452]
Hi,

While wanting to test `sysdig_monitor_notification_channel_ibm_event_notification` I initialized the provider as-is:
```hcl
provider "sysdig" {
  sysdig_monitor_url = "https://us-south.monitoring.cloud.ibm.com"
  ibm_monitor_iam_url = "https://iam.cloud.ibm.com"
  ibm_monitor_instance_id = data.ibm_resource_instance.sysdig_instance[0].guid
  ibm_monitor_api_key = "xxxxxx"
}
resource "sysdig_monitor_notification_channel_ibm_event_notification" "integrate_sysdig_on_en" {
    name                    = "xxxxxx"
    enabled                 = true
    instance_id             = ibm_resource_instance.event_notifications_instance[0].guid
    notify_when_ok          = true
    notify_when_resolved    = true
    share_with_current_team = false
}
```

The provider returns this error on an `apply` run:

> Error: missing user's current team

This parameter is marked optional. Why is it required by the resource ?

**Comment by dbonf** [comment]
hi, most probably your credentials were incorrect, either in instance id or api key, this is what you see when credentials are not correct _and_ you do not define either `sysdig_monitor_team_id` or `sysdig_monitor_team_name`. I agree we can work at proper error messages in this case.
