### ISSUE TITLE
Add support for platform metrics

### ISSUE THREAD

**Issue by dprosper** [sysdiglabs/terraform-provider-sysdig#56]
currently platform metrics is available in the ui, 
<img width="1164" alt="Screen Shot 2020-11-10 at 2 52 46 PM" src="https://user-images.githubusercontent.com/11874942/98726445-84675b80-2364-11eb-85ac-005cf8c8c7bd.png">

yet is not available in the provider;
https://github.com/sysdiglabs/terraform-provider-sysdig/blob/6d8b71ad7b1da3cc383f58772af6ee0d3b778694/sysdig/resource_sysdig_monitor_team.go#L52

**Comment by tembleking** [comment]
Thanks for reporting this @dprosper, will implement this soon :slightly_smiling_face:

**Comment by tembleking** [comment]
@dprosper it looks like this feature is for IBM only, I will need some support from our engineering team in order to implement this, stay tuned.
