### ISSUE TITLE
server error 500 when creating multiple teams in a loop

### ISSUE THREAD

**Issue by dprosper** [sysdiglabs/terraform-provider-sysdig#62]
i have a template that creates 6 teams using a for_each in the terraform template

```hcl
variable "teams" {
  description = "Map of teams and filter"
  default     = {
    "admin" = "agent.tag.team in (\"admin\")"
    "dev-a" = "agent.tag.team in (\"dev-a\")"
    "dev-b" = "agent.tag.team in (\"dev-b\")"
    "dev-c" = "agent.tag.team in (\"dev-c\")"
    "dev-d" = "agent.tag.team in (\"dev-d\")"
    "ops" = "agent.tag.team in (\"ops\")"
  }
}

resource "sysdig_monitor_team" "team" {
  for_each = var.teams

  name         = "${var.basename}-${each.key}"
  description  = var.team_description
  scope_by     = var.team_show
  filter       = each.value

  can_see_infrastructure_events = true

  entrypoint {
    type = "Explore"
  }
}
```

the first time i run `terraform apply` it creates 1 of the teams and 5 error 500 for the other teams.  running terraform apply the second time results in the other 5 teams created.   

the error in my terraform log is:
`{"timestamp":1606918078147,"status":500,"error":"Internal Server Error","message":"{\"errors\":[{\"reason\":\"system.error\",\"message\":\"Sorry, something really bad happened with your request (traceId: 4fa24c755faf28d7).\"}]}","path":"/api/users/light"}`

**Comment by dprosper** [comment]
If i create a team, delay 30 seconds and create the next 5 teams it works, so it feels like the issue is around creating the first team... ?

**Comment by tembleking** [comment]
Hello @dprosper, thanks for the feedback, I assume this is an onprem installation right? (I mean this is not our SaaS). If so, can you please provide more context regarding the 4fa24c755faf28d7 exception?

**Comment by dprosper** [comment]
this is an instance running in IBM Cloud (SaaS), I'll ask the internal team to see if they can provide you with the trace details.

**Comment by tembleking** [comment]
@dprosper could you check if this issue is still happening with the latest version? I feel like #65 should solve this issue as well.
