### ISSUE TITLE
Feature Request: Support policy assignment for images

### ISSUE THREAD

**Issue by JordanSussman** [sysdiglabs/terraform-provider-sysdig#66]
I would like the ability to manage policy assignment utilizing Terraform. You can currently utilize [this](https://secure.sysdig.com/#/scanning/policies/policy-assignments) UI page to assign policies for images.

Note: I'm not personally concerned with adding support for policy creation since the number of policies we intend to create is quite small compared to the amount of assignments.

**Comment by antoniobeyah** [comment]
@tembleking I have started working on this but have some questions on the design that would be a bit easier to talk through- are you available for a quick call to hammer out some of the details?  I can get a WIP pr up if that helps but the naming is a bit all over the place atm.  I had a hard time determining whether to align naming to the UI or the API.
