### ISSUE TITLE
website update required

### ISSUE THREAD

**Issue by ac427** [sysdiglabs/terraform-provider-sysdig#95]
https://sysdig.com/blog/sysdig-terraform-provider/

looks like there is no resource `sysdig_secure_notification_channel` in latest version. 
Is it possible to move all the examples to this repo?

```
[abc@foo 13:05:12 - monitors]$cat main.tf 
terraform {
  required_providers {
    sysdig = {
      source  = "sysdiglabs/sysdig"
    }

  }
}


provider "sysdig" {
  sysdig_monitor_api_token = var.sysdig_api_key
}

resource "sysdig_secure_notification_channel" "devops-email" {
  name                 = "DevOps e-mail"
  enabled              = true
  type                 = "EMAIL"
  recipients           = "devops@example.com"
  notify_when_ok       = false
  notify_when_resolved = false
}
[abc@foo 13:05:14 - monitors]$terraform plan

Error: Invalid resource type

  on main.tf line 15, in resource "sysdig_secure_notification_channel" "devops-email":
  15: resource "sysdig_secure_notification_channel" "devops-email" {

The provider provider.sysdig does not support resource type
"sysdig_secure_notification_channel".
```

**Comment by tembleking** [comment]
Thanks for reporting this, that blog post is a bit outdated. We will update it to use the new notification channels:
https://registry.terraform.io/providers/sysdiglabs/sysdig/latest/docs/resources/sysdig_secure_notification_channel_email

**Comment by tembleking** [comment]
@ac427 Website team updated the blog post with the new notification channel resources, feel free to reopen this issue if you encounter any other problem! :slightly_smiling_face:
