### ISSUE TITLE
Update docs to include that along with the team name being unique - it cannot exist in Monitor as well. 

### ISSUE THREAD

**Issue by magoh2000** [sysdiglabs/terraform-provider-sysdig#98]
Please update the line "name - (Required) The name of the Secure Team. It must be unique." to state  "name - (Required) The name of the Secure Team. It must be unique and not exist on Monitor."  It needs to be a little more explicit, as in the case of when a user is using the provider to create a team on Secure, they get the following in the debug, though the team name is NOT in Secure (though it does exist in Monitor): 

`{"errors":[{"reason":"Invalid request","message":"Team with name 'test-terraform' already exists"}]}
0
: timestamp=2021-04-20T11:11:47.503-0400
2021/04/20 11:11:47 [DEBUG] sysdig_secure_team.terratest: apply errored, but we're indicating that via the Error pointer rather than returning it: 422 Unprocessable Entity
2021/04/20 11:11:47 [ERROR] eval: *terraform.EvalApplyPost, err: 422 Unprocessable Entity
2021/04/20 11:11:47 [ERROR] eval: *terraform.EvalSequence, err: 422 Unprocessable Entity
`

**Comment by tembleking** [comment]
Thanks for the feedback @magoh2000, teams are shared between the products, that's the issue, I will update the docs and will be available in the next release. :slightly_smiling_face:
